config/routes.rb
Rails.application.routes.draw do

  root to: 'election#show'

  get '/election/:year' => 'election#show'
  get '/districts' => 'district#index'
  post '/districts' => 'district#search'
  get '/district/:name' => 'district#show'
  get '/district/:name/:year' => 'district#show'
  get '/about' => 'about#show'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <span><%= link_to "About Us", "/about" %></span>
  <% if current_page?(root_url) %>
    <span>Cover photo by Ryan Bushby</span>
  <% end %>
  <span>Vote BC <i class="fa fa-copyright" aria-hidden="true"></i> <%= Election.current_election_year %></span>
</div>

app/views/layouts/_parallax.html.erb
<div class="parallax">
  <div class="bg">
    <div class="translucent">
      <div class="search">
        <%= form_tag '/districts' do %>
          Enter your address or postal code: <%= text_field_tag :address, nil, class: "search-text" %>
          <%= submit_tag "Submit", class: "search-submit" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_top_nav.html.erb
<div class="navbar">
  <h3><%= link_to 'Vote BC', :root %></h3>
  <div class="menu-icon">
    <i class="fa fa-bars" aria-hidden="true"></i>
  </div>
  <div class="nav-menu">
   <%= link_to "Districts", districts_path, class: "button" %>
    <div class="dropdown button">
      <i class="fa fa-caret-right up" aria-hidden="true"></i>
      <button class="dropbtn">Elections</button>
      <div class="dropdown-content">
        <% elections.each do |e| %>
          <% if Election.current_election_year == e.year %>
            <%= link_to "#{e.year}", "/election/#{e.year}#buffer" %>
          <% else %>
            <%= link_to "#{e.year}", "/election/#{e.year}" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
  <head>

    <%
      title = "Vote BC"
      if @page_title
        title += " | #{@page_title}"
      end
    %>
    <title><%= title %></title>
    <%= csrf_meta_tags %>

    <% share_photo = "http://#{request.host}#{asset_path 'vote-bc-wide-cover.jpg'}" %>
    <% share_photo_ssl = "https://#{request.host}#{asset_path 'vote-bc-wide-cover.jpg'}" %>

    <!-- COMMON TAGS -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Search Engine -->
    <meta name="description" content="Data visualisation for BC Election History">
    <meta name="image" content="<%= share_photo %>">
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="<%= title %>">
    <meta itemprop="description" content="Data visualisation for BC Election History">
    <meta itemprop="image" content="<%= share_photo %>">
    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@votebcapp">
    <meta name="twitter:title" content="<%= title %>">
    <meta name="twitter:description" content="Data visualisation for BC Election History">
    <meta name="twitter:image:src" content="<%= share_photo %>">
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta property="og:title" content="<%= title %>">
    <meta property="fb:app_id" content="136130710263864">
    <meta property="og:description" content="Data visualisation for BC Election History">
    <meta property="og:image" content="<%= share_photo %>">
    <meta property="og:image:secure_url" content="<%= share_photo_ssl %>">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:site_name" content="Vote BC">
    <meta property="og:locale" content="en_US">
    <meta property="og:type" content="website">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:700" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if Rails.env.production? %>
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-98305669-1', 'auto');
      </script>
    <% end %>
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-590931e84018f1e1"></script>
  </head>

  <body>
    <%= render 'layouts/top_nav' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>